# Generated by Django 3.2.19 on 2024-01-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfCourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='points',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
