# Generated by Django 3.2.19 on 2024-01-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfCourses', '0002_golfcourse_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfcourse',
            name='point1long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='point2long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='point3long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='points1lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='points2lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='points3lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
