# Generated by Django 3.2.19 on 2024-01-02 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfCourses', '0003_auto_20240102_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfcourse',
            old_name='points1lat',
            new_name='point1lat',
        ),
        migrations.RenameField(
            model_name='golfcourse',
            old_name='points2lat',
            new_name='point2lat',
        ),
        migrations.RenameField(
            model_name='golfcourse',
            old_name='points3lat',
            new_name='point3lat',
        ),
    ]
