# Generated by Django 3.2.19 on 2023-11-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoDjango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='lat',
        ),
    ]
